var countries = [
    { id: 'AED', text: 'United Arab Emirates dirham (AED)' },
    { id: 'AFN', text: 'Afghan afghani (AFN)' },
    { id: 'ALL', text: 'Albanian lek (ALL)' },
    { id: 'AMD', text: 'Armenian dram (AMD)' },
    { id: 'ANG', text: 'Netherlands Antillean guilder (ANG)' },
    { id: 'AOA', text: 'Angolan kwanza (AOA)' },
    { id: 'ARS', text: 'Argentine peso (ARS)' },
    { id: 'AUD', text: 'Australian dollar (AUD)' },
    { id: 'AWG', text: 'Aruban florin (AWG)' },
    { id: 'AZN', text: 'Azerbaijani manat (AZN)' },
    { id: 'BAM', text: 'Bosnia and Herzegovina convertible mark (BAM)' },
    { id: 'BBD', text: 'Barbados dollar (BBD)' },
    { id: 'BDT', text: 'Bangladeshi taka (BDT)' },
    { id: 'BGN', text: 'Bulgarian lev (BGN)' },
    { id: 'BHD', text: 'Bahraini dinar (BHD)' },
    { id: 'BIF', text: 'Burundian franc (BIF)' },
    { id: 'BMD', text: 'Bermudian dollar (BMD)' },
    { id: 'BND', text: 'Brunei dollar (BND)' },
    { id: 'BOB', text: 'Boliviano (BOB)' },
    { id: 'BRL', text: 'Brazilian real (BRL)' },
    { id: 'BSD', text: 'Bahamian dollar (BSD)' },
    { id: 'BTN', text: 'Bhutanese ngultrum (BTN)' },
    { id: 'BWP', text: 'Botswana pula (BWP)' },
    { id: 'BYN', text: 'New Belarusian ruble (BYN)' },
    { id: 'BYR', text: 'Belarusian ruble (BYR)' },
    { id: 'BZD', text: 'Belize dollar (BZD)' },
    { id: 'CAD', text: 'Canadian dollar (CAD)' },
    { id: 'CDF', text: 'Congolese franc (CDF)' },
    { id: 'CHF', text: 'Swiss franc (CHF)' },
    { id: 'CLF', text: 'Unidad de Fomento (CLF)' },
    { id: 'CLP', text: 'Chilean peso (CLP)' },
    { id: 'CNY', text: 'Renminbi|Chinese yuan (CNY)' },
    { id: 'COP', text: 'Colombian peso (COP)' },
    { id: 'CRC', text: 'Costa Rican colon (CRC)' },
    { id: 'CUC', text: 'Cuban convertible peso (CUC)' },
    { id: 'CUP', text: 'Cuban peso (CUP)' },
    { id: 'CVE', text: 'Cape Verde escudo (CVE)' },
    { id: 'CZK', text: 'Czech koruna (CZK)' },
    { id: 'DJF', text: 'Djiboutian franc (DJF)' },
    { id: 'DKK', text: 'Danish krone (DKK)' },
    { id: 'DOP', text: 'Dominican peso (DOP)' },
    { id: 'DZD', text: 'Algerian dinar (DZD)' },
    { id: 'EGP', text: 'Egyptian pound (EGP)' },
    { id: 'ERN', text: 'Eritrean nakfa (ERN)' },
    { id: 'ETB', text: 'Ethiopian birr (ETB)' },
    { id: 'EUR', text: 'Euro (EUR)' },
    { id: 'FJD', text: 'Fiji dollar (FJD)' },
    { id: 'FKP', text: 'Falkland Islands pound (FKP)' },
    { id: 'GBP', text: 'Pound sterling (GBP)' },
    { id: 'GEL', text: 'Georgian lari (GEL)' },
    { id: 'GHS', text: 'Ghanaian cedi (GHS)' },
    { id: 'GIP', text: 'Gibraltar pound (GIP)' },
    { id: 'GMD', text: 'Gambian dalasi (GMD)' },
    { id: 'GNF', text: 'Guinean franc (GNF)' },
    { id: 'GTQ', text: 'Guatemalan quetzal (GTQ)' },
    { id: 'GYD', text: 'Guyanese dollar (GYD)' },
    { id: 'HKD', text: 'Hong Kong dollar (HKD)' },
    { id: 'HNL', text: 'Honduran lempira (HNL)' },
    { id: 'HRK', text: 'Croatian kuna (HRK)' },
    { id: 'HTG', text: 'Haitian gourde (HTG)' },
    { id: 'HUF', text: 'Hungarian forint (HUF)' },
    { id: 'IDR', text: 'Indonesian rupiah (IDR)' },
    { id: 'ILS', text: 'Israeli new shekel (ILS)' },
    { id: 'INR', text: 'Indian rupee (INR)' },
    { id: 'IQD', text: 'Iraqi dinar (IQD)' },
    { id: 'IRR', text: 'Iranian rial (IRR)' },
    { id: 'ISK', text: 'Icelandic króna (ISK)' },
    { id: 'JMD', text: 'Jamaican dollar (JMD)' },
    { id: 'JOD', text: 'Jordanian dinar (JOD)' },
    { id: 'JPY', text: 'Japanese yen (JPY)' },
    { id: 'KES', text: 'Kenyan shilling (KES)' },
    { id: 'KGS', text: 'Kyrgyzstani som (KGS)' },
    { id: 'KHR', text: 'Cambodian riel (KHR)' },
    { id: 'KMF', text: 'Comoro franc (KMF)' },
    { id: 'KPW', text: 'North Korean won (KPW)' },
    { id: 'KRW', text: 'South Korean won (KRW)' },
    { id: 'KWD', text: 'Kuwaiti dinar (KWD)' },
    { id: 'KYD', text: 'Cayman Islands dollar (KYD)' },
    { id: 'KZT', text: 'Kazakhstani tenge (KZT)' },
    { id: 'LAK', text: 'Lao kip (LAK)' },
    { id: 'LBP', text: 'Lebanese pound (LBP)' },
    { id: 'LKR', text: 'Sri Lankan rupee (LKR)' },
    { id: 'LRD', text: 'Liberian dollar (LRD)' },
    { id: 'LSL', text: 'Lesotho loti (LSL)' },
    { id: 'LYD', text: 'Libyan dinar (LYD)' },
    { id: 'MAD', text: 'Moroccan dirham (MAD)' },
    { id: 'MDL', text: 'Moldovan leu (MDL)' },
    { id: 'MGA', text: 'Malagasy ariary (MGA)' },
    { id: 'MKD', text: 'Macedonian denar (MKD)' },
    { id: 'MMK', text: 'Myanmar kyat (MMK)' },
    { id: 'MNT', text: 'Mongolian tögrög (MNT)' },
    { id: 'MOP', text: 'Macanese pataca (MOP)' },
    { id: 'MRO', text: 'Mauritanian ouguiya (MRO)' },
    { id: 'MUR', text: 'Mauritian rupee (MUR)' },
    { id: 'MVR', text: 'Maldivian rufiyaa (MVR)' },
    { id: 'MWK', text: 'Malawian kwacha (MWK)' },
    { id: 'MXN', text: 'Mexican peso (MXN)' },
    { id: 'MXV', text: 'Mexican Unidad de Inversion (MXV)' },
    { id: 'MYR', text: 'Malaysian ringgit (MYR)' },
    { id: 'MZN', text: 'Mozambican metical (MZN)' },
    { id: 'NAD', text: 'Namibian dollar (NAD)' },
    { id: 'NGN', text: 'Nigerian naira (NGN)' },
    { id: 'NIO', text: 'Nicaraguan córdoba (NIO)' },
    { id: 'NOK', text: 'Norwegian krone (NOK)' },
    { id: 'NPR', text: 'Nepalese rupee (NPR)' },
    { id: 'NZD', text: 'New Zealand dollar (NZD)' },
    { id: 'OMR', text: 'Omani rial (OMR)' },
    { id: 'PAB', text: 'Panamanian balboa (PAB)' },
    { id: 'PEN', text: 'Peruvian Sol (PEN)' },
    { id: 'PGK', text: 'Papua New Guinean kina (PGK)' },
    { id: 'PHP', text: 'Philippine peso (PHP)' },
    { id: 'PKR', text: 'Pakistani rupee (PKR)' },
    { id: 'PLN', text: 'Polish złoty (PLN)' },
    { id: 'PYG', text: 'Paraguayan guaraní (PYG)' },
    { id: 'QAR', text: 'Qatari riyal (QAR)' },
    { id: 'RON', text: 'Romanian leu (RON)' },
    { id: 'RSD', text: 'Serbian dinar (RSD)' },
    { id: 'RUB', text: 'Russian ruble (RUB)' },
    { id: 'RWF', text: 'Rwandan franc (RWF)' },
    { id: 'SAR', text: 'Saudi riyal (SAR)' },
    { id: 'SBD', text: 'Solomon Islands dollar (SBD)' },
    { id: 'SCR', text: 'Seychelles rupee (SCR)' },
    { id: 'SDG', text: 'Sudanese pound (SDG)' },
    { id: 'SEK', text: 'Swedish krona (SEK)' },
    { id: 'SGD', text: 'Singapore dollar (SGD)' },
    { id: 'SHP', text: 'Saint Helena pound (SHP)' },
    { id: 'SLL', text: 'Sierra Leonean leone (SLL)' },
    { id: 'SOS', text: 'Somali shilling (SOS)' },
    { id: 'SRD', text: 'Surinamese dollar (SRD)' },
    { id: 'SSP', text: 'South Sudanese pound (SSP)' },
    { id: 'STD', text: 'São Tomé and Príncipe dobra (STD)' },
    { id: 'SVC', text: 'Salvadoran colón (SVC)' },
    { id: 'SYP', text: 'Syrian pound (SYP)' },
    { id: 'SZL', text: 'Swazi lilangeni (SZL)' },
    { id: 'THB', text: 'Thai baht (THB)' },
    { id: 'TJS', text: 'Tajikistani somoni (TJS)' },
    { id: 'TMT', text: 'Turkmenistani manat (TMT)' },
    { id: 'TND', text: 'Tunisian dinar (TND)' },
    { id: 'TOP', text: 'Tongan paʻanga (TOP)' },
    { id: 'TRY', text: 'Turkish lira (TRY)' },
    { id: 'TTD', text: 'Trinidad and Tobago dollar (TTD)' },
    { id: 'TWD', text: 'New Taiwan dollar (TWD)' },
    { id: 'TZS', text: 'Tanzanian shilling (TZS)' },
    { id: 'UAH', text: 'Ukrainian hryvnia (UAH)' },
    { id: 'UGX', text: 'Ugandan shilling (UGX)' },
    { id: 'USD', text: 'United States dollar (USD)' },
    { id: 'UYI', text: 'Uruguay Peso en Unidades Indexadas (UYI)' },
    { id: 'UYU', text: 'Uruguayan peso (UYU)' },
    { id: 'UZS', text: 'Uzbekistan som (UZS)' },
    { id: 'VEF', text: 'Venezuelan bolívar (VEF)' },
    { id: 'VND', text: 'Vietnamese đồng (VND)' },
    { id: 'VUV', text: 'Vanuatu vatu (VUV)' },
    { id: 'WST', text: 'Samoan tala (WST)' },
    { id: 'XAF', text: 'Central African CFA franc (XAF)' },
    { id: 'XCD', text: 'East Caribbean dollar (XCD)' },
    { id: 'XOF', text: 'West African CFA franc (XOF)' },
    { id: 'XPF', text: 'CFP franc (XPF)' },
    { id: 'XXX', text: 'No currency (XXX)' },
    { id: 'YER', text: 'Yemeni rial (YER)' },
    { id: 'ZAR', text: 'South African rand (ZAR)' },
    { id: 'ZMW', text: 'Zambian kwacha (ZMW)' },
    { id: 'ZWL', text: 'Zimbabwean dollar (ZWL)' },
];
